create table produits (
    id bigint generated by default as identity,
    reference varchar(255) not null,
    nom varchar(255) not null,
    description varchar(255),
    quantite integer not null,
    emplacement varchar(255),
    primary key (id)
);

alter table produits
    add constraint idx_produit_reference unique (reference);

create table mouvements_stock (
    id bigint generated by default as identity,
    produit_id bigint not null,
    type enum ('ENTREE', 'SORTIE') not null,
    quantite integer not null,
    motif varchar(255) not null,
    date_mouvement timestamp(6) not null,
    primary key (id)
);

alter table mouvements_stock
    add constraint fk_mouvement_produit foreign key (produit_id) references produits (id);
